# filename: seed_database.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from pathlib import Path
import sqlite3

DB_PATH = Path("data/database.sqlite")


def main() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(DB_PATH) as connection:
        connection.executescript("""
            DROP TABLE IF EXISTS sales;
            DROP TABLE IF EXISTS customers;
            DROP TABLE IF EXISTS employees;

            CREATE TABLE sales (
                id INTEGER PRIMARY KEY,
                region TEXT NOT NULL,
                product TEXT NOT NULL,
                revenue REAL NOT NULL,
                date TEXT NOT NULL,
                units_sold INTEGER NOT NULL
            );

            CREATE TABLE customers (
                id INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                industry TEXT NOT NULL,
                churn_date TEXT,
                satisfaction_score REAL NOT NULL
            );

            CREATE TABLE employees (
                id INTEGER PRIMARY KEY,
                department TEXT NOT NULL,
                satisfaction_score REAL NOT NULL,
                tenure_years REAL NOT NULL
            );
        """)

        connection.executemany(
            "INSERT INTO sales VALUES (?, ?, ?, ?, ?, ?)",
            [
                (1, "East", "Analytics Platform", 120000, "2026-01-15", 24),
                (2, "West", "Analytics Platform", 150000, "2026-01-20", 30),
                (3, "North", "Analytics Platform", 110000, "2026-02-14", 22),
                (4, "South", "Analytics Platform", 98000, "2026-01-30", 19),
                (5, "East", "Risk Dashboard", 87000, "2026-02-10", 18),
                (6, "West", "Risk Dashboard", 92000, "2026-03-11", 20),
                (7, "North", "Risk Dashboard", 84000, "2026-04-26", 17),
                (8, "South", "Risk Dashboard", 73000, "2026-05-02", 14),
                (9, "East", "Data Integration", 79000, "2026-04-04", 16),
                (10, "West", "Data Integration", 132000, "2026-04-18", 25),
                (11, "North", "Data Integration", 76000, "2026-03-05", 15),
                (12, "South", "Data Integration", 68000, "2026-02-25", 14),
            ],
        )

        connection.executemany(
            "INSERT INTO customers VALUES (?, ?, ?, ?, ?)",
            [
                (1, "Apex Manufacturing", "Manufacturing", None, 4.4),
                (2, "Bright Retail", "Retail", "2026-02-15", 2.8),
                (3, "Cedar Health", "Healthcare", None, 4.1),
                (4, "Delta Finance", "Financial Services", "2026-03-20", 2.9),
                (5, "Evergreen Energy", "Energy", None, 3.8),
                (6, "Frontier Logistics", "Transportation", None, 4.0),
                (7, "Granite Media", "Media", "2026-04-12", 2.5),
                (8, "Harbor Technology", "Technology", None, 4.6),
            ],
        )

        connection.executemany(
            "INSERT INTO employees VALUES (?, ?, ?, ?)",
            [
                (1, "Consulting", 4.3, 3.5),
                (2, "Consulting", 4.0, 2.0),
                (3, "Audit", 3.7, 5.0),
                (4, "Audit", 3.9, 4.0),
                (5, "Tax", 4.2, 6.5),
                (6, "Tax", 3.8, 2.5),
                (7, "Operations", 3.5, 1.5),
                (8, "Operations", 3.9, 7.0),
            ],
        )

    print(f"Created {DB_PATH}")


if __name__ == "__main__":
    main()
