# filename: agents/manager.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import os
import re

from dotenv import load_dotenv
from google import genai
from google.genai import types

from agents import qualitative, quantitative
from tokenomics.logger import log
from validation.validator import (
    validate_qualitative,
    validate_quantitative,
)

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise RuntimeError("GEMINI_API_KEY is not configured")

client = genai.Client(api_key=API_KEY)

MANAGER_MODELS = tuple(
    dict.fromkeys(
        (
            os.getenv("GEMINI_MANAGER_MODEL", "gemini-3.8-flash"),
            os.getenv("GEMINI_MODEL", "gemini-3.5-flash-lite"),
        )
    )
)

QUANTITATIVE_TERMS = (
    "revenue",
    "sales",
    "churn",
    "metric",
    "metrics",
    "number",
    "numbers",
    "total",
    "average",
    "percentage",
    "percent",
    "trend",
    "trends",
    "compare",
    "comparison",
    "highest",
    "lowest",
    "ranking",
    "growth",
    "units sold",
    "by region",
    "by department",
    "quarterly",
    "monthly",
    "q1",
    "q2",
    "q3",
    "q4",
    "sql",
)

QUALITATIVE_TERMS = (
    "policy",
    "policies",
    "process",
    "processes",
    "procedure",
    "procedures",
    "explain",
    "explanation",
    "guideline",
    "guidelines",
    "security",
    "code review",
    "document",
    "documents",
    "requirement",
    "requirements",
    "standard",
    "standards",
)


def extract_response_text(response) -> str:
    try:
        direct_text = response.text or ""
    except Exception:
        direct_text = ""

    if direct_text.strip():
        return direct_text.strip()

    text_parts = []

    for candidate in getattr(response, "candidates", []) or []:
        content = getattr(candidate, "content", None)

        for part in getattr(content, "parts", []) or []:
            part_text = getattr(part, "text", "") or ""

            if part_text.strip():
                text_parts.append(part_text.strip())

    return " ".join(text_parts).strip()


def get_token_usage(response) -> tuple[int, int]:
    usage = getattr(response, "usage_metadata", None)

    input_tokens = int(
        getattr(usage, "prompt_token_count", 0) or 0
    )

    output_tokens = int(
        getattr(usage, "candidates_token_count", 0) or 0
    )

    return input_tokens, output_tokens


def contains_term(query: str, term: str) -> bool:
    pattern = rf"\b{re.escape(term)}\b"
    return re.search(pattern, query, re.IGNORECASE) is not None


def fallback_route(query: str) -> str:
    quantitative = any(
        contains_term(query, term)
        for term in QUANTITATIVE_TERMS
    )

    qualitative = any(
        contains_term(query, term)
        for term in QUALITATIVE_TERMS
    )

    if quantitative and qualitative:
        return "both"

    if quantitative:
        return "quantitative"

    return "qualitative"


def classify(query: str) -> str:
    prompt = f"""
Classify this query as exactly one of: qualitative, quantitative, both.

qualitative = questions about policies, processes, procedures,
explanations, or documentation.

quantitative = questions about numbers, metrics, trends,
comparisons, or SQL-queryable data.

both = questions that need both document search and data analysis.

Query: {query}

Reply with one word only: qualitative, quantitative, or both.
""".strip()

    last_error = None

    for model_name in MANAGER_MODELS:
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.0,
                    max_output_tokens=10,
                ),
            )

            raw_route = extract_response_text(response).casefold()

            match = re.search(
                r"\b(qualitative|quantitative|both)\b",
                raw_route,
            )

            if not match:
                raise ValueError(
                    f"Invalid manager response: {raw_route!r}"
                )

            input_tokens, output_tokens = get_token_usage(response)
            route = match.group(1)

            log(
                query,
                "manager-classifier",
                input_tokens,
                output_tokens,
            )

            print(f"[Manager] Model used: {model_name}")

            return route

        except Exception as error:
            last_error = error

            print(
                f"[Manager] {model_name} unavailable; "
                "trying the next model."
            )

    route = fallback_route(query)

    print(
        "[Manager] Gemini classification failed; "
        f"using local fallback: {route} "
        f"({type(last_error).__name__})."
    )

    log(
        query,
        "manager-classifier-fallback",
        0,
        0,
    )

    return route


def run(query: str):
    print(f"\nQuery: {query}")

    route = classify(query)
    print(f"Route: {route}")

    qual_result = None
    quant_result = None

    if route in ("qualitative", "both"):
        qual_result = qualitative.run(query)

        validation = validate_qualitative(
            qual_result["answer"],
            qual_result["chunks"],
        )

        log(
            query,
            "qualitative",
            qual_result["input_tokens"],
            qual_result["output_tokens"],
        )

        if validation["flag"]:
            print(
                "\nVALIDATION WARNING: "
                f"{validation['warning']}"
            )

        print(
            f"\n[Qualitative]\n"
            f"{qual_result['answer']}"
        )

    if route in ("quantitative", "both"):
        quant_result = quantitative.run(query)

        validation = validate_quantitative(
            quant_result["answer"],
            quant_result["sql"],
            quant_result["validation"],
        )

        log(
            query,
            "quantitative",
            quant_result["input_tokens"],
            quant_result["output_tokens"],
        )

        if validation["flag"]:
            print(
                "\nVALIDATION WARNING: "
                f"{validation['warning']}"
            )

        print(
            f"\n[Quantitative]\n"
            f"{quant_result['answer']}"
        )

        print(f"SQL used: {quant_result['sql']}")

    return {
        "route": route,
        "qualitative": qual_result,
        "quantitative": quant_result,
    }
